name: Update Data Files

on:
  discussion:
    types: [created]

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Parse discussion
      id: parse
      run: |
        DATA=$(grep -oP '\|\|DATA\|\|\K.*?(?=\|\|MANIFEST\|\|)' <<< "${{ github.event.discussion.body }}")
        MANIFEST=$(grep -oP '\|\|MANIFEST\|\|\K.*' <<< "${{ github.event.discussion.body }}")
        echo "::set-output name=data::$DATA"
        echo "::set-output name=manifest::$MANIFEST"
        
    - name: Update files
      run: |
        echo '${{ steps.parse.outputs.data }}' > data.json
        echo '${{ steps.parse.outputs.manifest }}' > manifest.json
        
    - name: Commit changes
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add data.json manifest.json
        git commit -m "Actualización automática de datos desde discussion #${{ github.event.discussion.number }}"
        git push